# Generated by Django 6.0.3 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('cash', 'Cash'), ('translation', 'Translation')], default='created', max_length=20),
        ),
    ]
