# Generated by Django 6.0.3 on 2026-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments_payment_url_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
